Add game
perhells/elo-pong pull request #2
Opened 2023-12-06 11:59 UTC by perhells

2023-12-06 12:30 UTC, jannissioustis approved these changes

2023-12-06 12:30 UTC, jannissioustis commented on calculate_ratings.py
> +    print("This is a Python script that calculates ELO ratings for ~casual~ very serious table tennis games.\n")
⭐

2023-12-06 12:30 UTC, jannissioustis commented on README.md
> +2. Jannis: 1156
😢

2023-12-13 08:38 UTC, pattez requested changes

2023-12-13 08:38 UTC, pattez commented on README.md
> +1. Per: 1244
Stämmer det här?
Verkar vara något fel på algo:n kanske?

2023-12-20 09:10 UTC, merged